### ISSUE TITLE
Use of uninitialized value in regexp compilation

### ISSUE THREAD

**Issue by Gazoo** [spamhaus/spamassassin-dqs#13] opened 2019-07-17 16:13 UTC
After installation I get this when running `spamassassin --lint`

```
# spamassassin --lint
Jul 17 10:09:58.262 [10213] warn: Use of uninitialized value in regexp compilation at /usr/share/perl5/vendor_perl/Mail/SpamAssassin/Plugin/SH.pm line 69.
Invalid database type 0
````
OS version:
```# cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core) 
```
SpamAssassin version:

```
# spamassassin -V
SpamAssassin version 3.4.3-rc2 running on Perl version 5.16.3
```

**Comment by Gazoo** [comment] 2019-07-17 16:24
It looks like that block of code was taken from a very old HashBl.pm. Why not use the updated code that is included by default in the new SpamAssassin?

https://github.com/apache/spamassassin/blob/trunk/lib/Mail/SpamAssassin/Plugin/HashBL.pm#L251

**Comment by ricalfieri** [comment] 2019-07-18 12:34
Could you confirm that replacing the  $self->{email_re} in SH.pm with the one from HashBL.pm (from SpamAssassin trunk) solves the problem? I don't have a system like your to test it and I'd prefer to wait for 3.4.3 to be officially released before debugging on a release candidate

**Comment by Gazoo** [comment] 2019-07-18 13:26
Unfortunately changing $self->{email_rex} to $self->{email_re} doesn't fix it. I wonder why the HashBL.pm code works fine while the code in SH.pm doesn't ?

**Comment by Gazoo** [comment] 2019-07-18 13:45
If you need the RPM package for testing here is the RPM that I'm using. It was built for Centos 7:
https://www.danami.com/spamassassin-3.4.3-0.20190617svn1861513.el7.x86_64.rpm

**Comment by ricalfieri** [comment] 2019-07-19 13:57
Alright, I managed to reproduce the problem. If you do a 

spamassassin --lint -D

You'll probably see the lines:

Jul 19 15:34:50.457 [63775] dbg: HashBL: local tests only, disabling HashBL
Jul 19 15:34:50.405 [63775] dbg: SHPlugin: local tests only, disabled

The problem is that our plugin doesn't handle very nicely not having network tests enabled, so it throws that error.

I now pushed a fixed version (also with the better email regex, thanks for pointing that out) , but you should check why you have network checks disabled

**Comment by Gazoo** [comment] 2019-07-19 14:06
We don't have network tests disabled. Doesn't spamassassin --lint disable network tests automatically? As you can see from our spam stats Pyzor, Razor2, and HashBL all are working without issue.

![2019-07-19_08h02_54](https://user-images.githubusercontent.com/379016/61540982-f5f6fa00-a9fb-11e9-8cbf-2167bf4a7aea.png)

**Comment by ricalfieri** [comment] 2019-07-19 14:10
Maybe something changed on 3.4.3 .. the error was because the function $self->{main}->{registryboundaries}->{valid_tlds_re} apparently doesn't load when linting (that could make sense if network tests are disabled)

However, did you fetch the latest SH.pm and tried?

**Comment by Gazoo** [comment] 2019-07-19 14:20
The updated version doesn't spit out any error now when running `spamassassin --lint` with SpamAssassin 3.4.3 RC3

Also running `spamassassin --lint -D`
```
Jul 19 08:17:21.145 [27428] dbg: SHPlugin: local tests only, disabled
```

Looks like its fixed. Thanks again!

**Comment by ricalfieri** [comment] 2019-07-19 14:57
closing this, thanks to you again for pointing out the outdated regex :)

**Closed by ricalfieri** 2019-07-19 14:57 UTC
